apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-12
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 158.108.38.88
    path: /var/nfsshare
