apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: wurstmeister/zookeeper
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
